# Generated by Django 4.1.3 on 2022-11-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_name_man_nam'),
    ]

    operations = [
        migrations.AddField(
            model_name='man',
            name='kam',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
