# Generated by Django 4.1.3 on 2022-11-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_man_kam'),
    ]

    operations = [
        migrations.AddField(
            model_name='man',
            name='umer',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
