# Generated by Django 4.1.3 on 2022-11-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_man_umer'),
    ]

    operations = [
        migrations.AddField(
            model_name='man',
            name='date',
            field=models.DateTimeField(default='2022-10-3'),
            preserve_default=False,
        ),
    ]
