# Generated by Django 4.1.3 on 2022-11-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_man_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='man',
            old_name='kam',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='man',
            name='date',
        ),
        migrations.RemoveField(
            model_name='man',
            name='umer',
        ),
        migrations.AddField(
            model_name='man',
            name='email',
            field=models.EmailField(default='email', max_length=254),
            preserve_default=False,
        ),
    ]
