# Generated by Django 4.1.3 on 2022-11-17 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_userlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Man',
        ),
    ]
