# Generated by Django 4.1.3 on 2022-11-17 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_alter_userlog_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlog',
            name='name',
        ),
        migrations.AddField(
            model_name='userlog',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
